### PR TITLE
cmake: use post-reorg path to FindHIP.cmake

### PR DESCRIPTION
**Pull request by evetsso**

### CODE REVIEW

**Comment by evetsso** [comment]
Hmm.. it gets a little farther, but wants to know HIP_ROOT_DIR now.  I know I've had to do that when I build hipFFT myself on Nvidia.. I don't know it that's supposed to happen or not.

**Comment by evetsso** [comment]
Now we're seeing a failure due to hipcc not being present.  Opened https://github.com/ROCmSoftwarePlatform/rocJenkins/pull/627 to try to deal with that.

**Review by stanleytsang-amd — APPROVED** [review]
LGTM, but if @lawruble13 can also take a look, that'd be great.

**Review by lawruble13 — APPROVED** [review]
This looks good to me, noting for the future that we should be able to simplify all of this as we can include HIP via config mode for both AMD and NVIDIA products.

**Comment by evetsso** [comment]
Merging.  Windows build had some trouble that looks like it'll be fixed by https://github.com/ROCmSoftwarePlatform/hipRAND/pull/74 when that gets merged to develop.

**Pull request merged**
